# config.yml


# max distance for trading
max-trade-distance: 10.0

# All messages are located in "lang/lang_**.yml" (ie. "lang/lang_en.yml")
lang: en

# Can you trade with yourself ? You probably don't want that. Used for debugging purpose.
self: false

# How much XP add by each click. Shift-clicking multiply this value by 10
xp-amount: 5