CREATE TABLE IF NOT EXISTS Offer(
  id INTEGER PRIMARY KEY,
  uuid CHAR(36),
  items TEXT,
  money DECIMAL(11, 2)
);

CREATE TABLE IF NOT EXISTS Trade(
  id INTEGER PRIMARY KEY,
  date_recorded DATETIME
);

CREATE TABLE IF NOT EXISTS Link(
  tradeID INTEGER,
  offerID INTEGER
);