# config.yml
self: true

# max distance for trading
max-trade-distance: 10.0

# All messages are located in "lang/lang_**.yml" (ie. "lang/lang_en.yml")
lang: fr

layout:
  empty:
  confirm:
  money-plus:
  money-minus:
  status-waiting:
  status-ok: